version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8.4

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install
          command: |
            python -m venv venv
            source venv/bin/activate
            pip install .[dev]

      - run:
          name: run tests
          command: |
            source venv/bin/activate
            pytest
      - store_artifacts:
          path: test-reports
          destination: test-reports