version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8.4

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install
          command: |
            python -m venv venv
            source venv/bin/activate
            pip install .[dev]

      - run:
          name: run tests and generate coverage
          command: |
            source venv/bin/activate
            coverage run -m pytest
            coverage html

      - run:
          name: upload coverage to codecov
          command: bash <(curl -s https://codecov.io/bash)

      - store_artifacts:
          path: test-reports
          destination: test-reports